# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
name: Selenium Conference
description: "Home of all of the selenium conferences."
baseurl:
url: http://seleniumconf.com
title: Selenium Conference Home
email: andrew@lazycoder.io

#url: "https://nirgn975.github.io/andrewmkrug" # the base hostname & protocol for your site
twitter_username: lazycoderio
github_username:  andrewmkrug

# Build settings
permalink: /:categories/:title/
sass:
  style: compressed
paginate: 5
paginate_path: "/:num/"
markdown: kramdown
permalink: pretty

collections:
- conferences

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-gist

exclude: [
  "node_modules",
  "LICENSE",
  "package.json",
  "README.md",
  "Gemfile",
  "gulpfile.babel.js",
  ".babelrc",
  ".gitignore",
  "sass",
  "scss",
  "validate"
]
